components/DatePicker/Simple/index.js

Can you please check this code and merge if it is ok!

feat: add minDate property in Simple DatePicker component

---

containers/TabMenu/actionTypes.js
containers/TabMenu/actions.js
containers/TabMenu/reducers.js

feat: UIS-450 add update title action for the tabmenu container

---

components/Input/index.js

This is a quick fix. The better approach would be to use cacheId concept. However, since this component will be refactored on this stage there is no need to put extra development effort in component that will be refactored.

Fix input error message

---

components/DatePicker/Simple/index.js
components/DatePicker/style.css

Can you please check this code and merge if it is OK.

feat: add validation capabilities to DatePicker

---

components/DatePicker/Simple/index.js
components/DatePicker/style.css

Can you please check this code and merge if it is ok.

Fixing errors with datepicker for the new updates

---

components/SimpleGrid/Body/Column.js
components/SimpleGrid/Header/Field.js
components/SimpleGrid/Header/index.js
components/SimpleGrid/index.js

BREAKING CHANGE: transform cell value now supports transform header title, breaking change is +1 param in method called  which chould be handled correctly

perf(transformCellValue): transform header value too

---

components/Layout/Col.js
components/Layout/Container.js
components/Layout/Row.js
components/Layout/Vertical.js
components/Layout/index.js
components/Layout/style.css

Added new components for layout

Feat uis 299

---

containers/DateFormatter/index.js

- to not show NaN:NaN:NaN
- make login date immutable

fix: not well formatted date:

---

components/BusinessUnits/index.js
components/BusinessUnits/styles.css
components/BusinessUnitsTree/index.js
components/BusinessUnitsTree/style.css
components/CollapsableContent/style.css
components/ResiziblePageLayout/Container.js

Please make code review, @simeonpp

fix: UIS-1783 fix bug about multiple scrollbars for the BU tree

---

components/GridToolBox/index.js
components/GridToolBox/types.js

Add customSearch (combination from DropDown and SearchBox) to filter types in GridToolBox component.

feat: Add customSearch to filters

---

components/DateTimePicker/Between/index.js
components/DateTimePicker/Simple/index.js
components/SearchBox/index.js

Hi Kalin, Here I have added innerWrapperClassname property to control data timp picker styles externally and added onchange event at search type input. Please merge the changes If you are fine. Thank you.

feat: add classes to control date time picker input styles 

---

components/CompareGrid/helpers.js

Add option to mark all fields as removed in CompareGrid when deleting an Entity.

Fix: UIS-1380

---

components/PageLayout/Header.js
components/PageLayout/style.css

Fix maker/checker (and not only) buttons displacement when header title is too long.

Fix: UIS-2688

---

components/Grid/HeaderCell.js

Bug was encountered when trying to make Header Cells non sort-able.

Fixed bug which didn't disable sorting on columns.

---

components/Input/index.js

extend input to use external styles

fix MCTUNE-2598

---

components/Grid/HeaderCell.js
components/Grid/style.css
components/SimpleGrid/Header/styles.css

Reverts softwaregroup-bg/ut-front-react#370

Revert "RCR2-920: fix grid sort styling:"

---

components/SearchBox/index.js

SearchBox component now trims the search string before searching.
Closes ABTN-3361

fix(ABTN-3361): Trim surrounding whitespaces in search fields

---

components/Autocomplete/AutoFetcher.js

- Add property to autoFetcher for passing an external onChange
function named onSearchTextInput. If defined,the function is
invoked before the debounced onChange

fix(ABTN-3469) : [ABZ] System Alerts: After clicking on Create button,the username is still displayed

---

containers/TabContainer/validator.js

- Add text validations for integer numbers and ranges

[ABZ] Customers: An error message appears when User fill in greater number in Number of Family Members / Number of Owners

---

containers/TabContainer/index.js
containers/TabContainer/validator.js

@BozhidarTodorov - I'm sending this on behalf of Behrin.
Add key property in errosObj in validation.
Closes ABTN-3749.

fix(ABTN-3749): Missing field key in the error message

---

containers/TabContainer/index.js
containers/TabContainer/validator.js

Set addtiional property to TabContainer to change label
in Notification pop-up.
Closes ABTN-3814.

fix(ABTN-3814): Set additional param for element label

---

containers/TabContainer/validator.js

- Fix incorrect if condition causing a regression in the components using a tab container
- Lint validator file
Closes ABTN-3831

fix(ABTN-3831) : User cannot go to assigned users tab in the Alerts screen

---

components/HeaderNew/HeaderProfileInfo.js

fix: make button 'Help' visible

---

components/Input/style.css

Set gray colour for diasabled element in multiselect element
Closes ABTN-3835.

fix(ABTN-3835): Edit disabled element in multiselect

---

components/Input/MultiSelectDropdown.js

- Disable dropdown menu items
- Add property for disabling the select all button

fix(ABTN-3835): [ABZ] System Alerts: The selected delivery channel is colored in blue when User click on it

---

helpers.js

PAP: Internal Accounts: incorrect amount of decimals after comma UA-286

---

components/DocumentUpload/Camera.js

Fix/ACM-792 : Fix broken url object due to which video didn't start
Fix broken url object due to which video didn't start
Closes: ACM-792

Fix for ACM-792

---

containers/LoginForm/actions.js

fix(CEM-1067): change forgot password method

---

components/DocumentUpload/Cropper.js
components/DocumentUpload/index.js

Id photo resize not working correctly in adding photo documents in Documents tab.
Closes: ACM-1123

FIX:(ACM-1123) - id photo resize not working correctly in document tab.

---

containers/LoginForm/reducer.js

- Change text of message
Closes CEM-1448

fix(CEM-1448) : PAP / Forgotten password: Incorrect message after OTP sending

---

components/ResiziblePageLayout/Container.js

[Alerts] Cannot read property 'currentWidth' of undefined when try to hide Alert details	
Closes: ACM-1317

FIXX:(ACM-1317) - Error onResizing side columns

---

containers/Documents/helpers.js
containers/DocumentsObject/helpers.js

fix(CEM-1932): send param actorId to documents

---

containers/DocumentsObject/helpers.js

fix(CEM-2203): remove undeclared variable

---

components/DatePicker/Between/index.js
components/DatePicker/Between/style.css
components/DatePicker/style.css

fix(ABTN-4275): change css

---

validator/index.js

appears when User create a new alert
- Take into account the length of the untrimmed value when validating
Closes CEM-1931

fix (CEM-1931) : PAP / System Alerts: An error message

---

containers/LoginForm/reducer.js

This PR resolves issue where validation errors are cleared after input value is changed.

fix: resolved CEM-2287 validation errors not cleared

---

components/CompareGrid/index.js

- add className property to CompareGrid component

fix (CEM-2271, 2272): PAP / Document Management: Document section is not aligned when User upload a new file with longer description

---

validator/index.js

- add check for null property to be excluded from validation

fix (CEM-2446): PAP / Business Units: Max length validation should be implemented for Account Number field

---

package.json
ui/middleware.js

https://github.com/immutable-js/immutable-js/issues/450#issuecomment-123826474

remove unreliable check

---

package.json
styleguidist/package.json
ui/index.js
ui/wrapper.js

split menu items  - each module to provide their own menu items

feat: split menu items  - each module to provide their own

---

components/GridToolBox/index.js

fix: pass placeholderValue on

---

containers/LoginForm/config.js

fix(CEM-4077): [PAP 34] Application is vulnerable to username / national id / wallet id enumeration

---

components/DocumentUpload/index.js

- extension is already present in originalFilename

fix(CEM-4146): PAP - Denial of service - Upload document with unlimited size - Error not correct

---

components/Form/index.js
components/FormInput/index.js
containers/LoginForm/index.js

I'm not a robot checkbox being marked
- Fix setting of value for the captcha input
-Fix fatal error on login
Closes CEM-4337

fix(CEM-4337) : PAP - CAPTCHA - Login successful only with

---

containers/LoginForm/index.js
containers/LoginForm/style.css

- Align captcha input with the rest of the form

fix : Align captcha with the rest of the form

---

components/AdvancedPagination/index.js
components/Box/index.js
components/CollapsableContent/index.js
components/CompareGrid/index.js
components/DateTimePicker/Simple/index.js
components/DocumentUpload/AddFileButton.js
components/ErrorWindow/index.js
components/Filters/ByCustomSearch/index.js
components/Grid/HeaderCell.js
components/GridToolBox/index.js
components/Input/Checkbox.js
components/Input/Dropdown.js
components/Input/Radio.js
components/Input/TextArea.js
components/Input/index.js
components/Loader/index.js
components/PageLayout/Header.js
components/Popup/Header.js
components/SimpleGrid/Body/index.js
components/SimpleGrid/Header/Field.js
components/SimpleGridToolbox/index.js
components/StandardButton/index.js
components/Tab/MultiTab.js
components/Tab/Tab.js
components/TabMenu/TabLink.js
components/TitledContentBox/index.js

some components were modified and were not wrapping text with the <Text> component. In this update, the only change is to wrap strings with the <Text> component

fix translations by wrapping text messages with <TEXT> component

---

components/Autocomplete/index.js
components/Autocomplete/style.css
package.json

- Added Autocomplete component by using the one found in @material-ui/lab

feat (NSM-172) : Autocomplete component

---

components/Autocomplete/index.js

- Add property for required field 
- Add property for handling component validation

fix (NSM-172) : Autocomplete components

---

components/DatePicker/Between/index.js
components/GridToolBox/index.js
components/Input/ButtonInput.js
components/Input/Dropdown.js

- added Text component to enable translation for some components

enabled translation to some components

---

components/DatePicker/Simple/index.js
components/DateTimePicker/Simple/index.js
components/DateTimePicker/Simple/style.css

fix/(PSTB-3984): Incorrectly displayed fields

---

components/DatePicker/Simple/index.js

@behrindzhambaz , @stoberov , @pavelGeorgievSG

fix/(PSTB-3984): make datePicker full width

---

components/DateTimePicker/Simple/index.js

reports
- Fix date formatting string in date picker

fix (MSA-425) : Error when opening transfer list

---

components/Layout/verticalStyles.css
package.json

Fix version number to allow jenkins builds to complete

---

containers/Gate/helpers.js

fix/(PSTB-4517): Users cannot upload document

---

assets/index.css

@behrindzhambaz , @pavelGeorgievSG

fix/(MSA-251): check prop. work customer in USP

---

constants.js

Свързани МР: https://git.softwaregroup.com/ut5/ut-customer/merge_requests/1785, https://git.softwaregroup.com/ut5impl/impl-mwallet/merge_requests/285

UTM-110: Change documentPrefix.

---

components/GridToolBox/style.css

@pavelGeorgievSG , @stoberov , @BozhidarTodorov

fix/(PSTB-4626): Postbank wallet / Update 2 Release 1 mail

---

components/DataList/KeyValueRow/index.js
components/DataList/KeyValueRow/style.css

Before:
After:
FYI @behrindzhambaz / @KrasimirGenchev / @BozhidarTodorov

fix (MSA-866): improve DataList row styling

---

components/Input/index.js

Fix an issue with displaying values in the Input field where renderText method is not explicitly defined

Fix an issue with displaying values in the Input field

---

containers/LoginForm/actions.js

fix(CEM-5309) : E-wallet channels DOS

---

components/DateTimePicker/Simple/index.js
components/DateTimePicker/Simple/style.css

Прикачвам файлове преди и след промените.
Сега:
Преди:

fix/(MSA-935): Transfer reports: Date pickers

---

components/DatePicker/Between/index.js

- remove the datepicker's vaues dependence on
state. Use only props in this case

fix (PSTB-5608,ECNT-1464) : Incorrectly setting filter dates

---

components/DocumentUpload/helpers.js
components/DocumentUpload/index.js
containers/Documents/actions.js

…or returned when document uploaded is too large

fix(MSA-1185):[USP] Customers/ Document upload: Not user-friendly error returned when document uploaded is too large

---

components/Input/index.js

@BozhidarTodorov , @pavelGeorgievSG , @stoberov , @NKozhuharski

fix/(MSA-1710): Referral page opens empty

---

components/DocumentUpload/index.js
components/Documents/FileDetailsPopup.js
components/Documents/Toolbox.js
package.json

fix/(PSTB-6268): Documents tab/ Back of id card

---

components/SimpleGridToolbox/index.js
components/SimpleGridToolbox/style.css

Този MR върви в комбина с още 1 MR в ut-notice от току-що.
AFTER:
@BozhidarTodorov @yavor-h-ivanov @KrasimirGenchev @NKozhuharski

fix (MSA-2149): [PAP] System alerts/ Filer by row broken design

---

components/Documents/DocumentUploadWithForm.js

- Show country dropdown only if a countries array is provided
- Set default props for the countries array

fix (ECNT2-1075) : Fatal error when opening Add document

---

components/Grid/Header.js
components/Grid/HeaderCell.js
components/Grid/IrregularHeader.js
components/Grid/index.js

Added functionality for irregular headers to cater for the agent termination report

NMB-1111 added functionality for irregular headers on Grid

---

components/DatePicker/Simple/index.js
components/DatePicker/style.css
components/DateTimePicker/Simple/index.js
components/DateTimePicker/Simple/style.css
package.json

fix/(MSA-935): Transfer reports: Date pickers and time pickers incorrect ui

---

components/DataGrid/index.js
package.json

added document preview on maker checker screen

---

utils/helpers.js

- Provide default return value from the helper function

fix (ECNT-1495) : Fatal error on documents tab

---

components/SimpleGridToolbox/style.css

fix(MSA-2764): It is visible gray rectangle

---

components/Documents/Listing.js
components/Documents/Toolbox.js
components/Tab/Tab.js

style: show all table items ALZMFAC-663

---

components/Documents/DocumentsGrid.js
components/Documents/Listing.js
components/Documents/Toolbox.js
components/Documents/style.css
components/Tab/Tab.js
utils/helpers.js

Alzmfac 663

---

components/AdvancedSearchButton/style.css
components/Tab/Tab.js

- Adjust advanced button height

fix (ECNT2-2571) : Advanced search button height

---

components/Tab/Tab.js
ui/middleware.js

Fix file upload issue due to methodParams.toJS() distorting the formData payload.

fix(File Upload) Fix file upload issue  NMB-2247

---

containers/TabContainer/index.js

Added translate functionality to specific component

Fix. Added translate functionality to component. VAB-2546

---

components/DateTimePicker/Simple/index.js
components/MaterialUILayout/index.js
ui/index.js

and set default color to be primary color

feat: add option to change color in DatePicker BDC-2427

---

components/Input/Dropdown.js

- Add validation for required dropdown fields

fix(MSA-4186): additional validation

---

components/GridToolBox/index.js
components/GridToolBox/style.css
components/GridToolBox/types.js
components/Iframe/index.js
components/Iframe/style.css

fix card number filter by adding iframe from ut-card
filter reports by press enter button

fix: card number filter, add enter key press event PS-282

---

components/GridToolBox/index.js

ref do not work without forwardRef: true in connect

fix: refs with connect PS-283

---

CHANGELOG.md
components/DocumentUpload/Camera.js
components/DocumentUpload/index.js
package.json

- this feature adds support for modern browsers updating deprecated Apis. ref https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia
- Backward compatibility is maintained
- Functional components are used in place of class components

Fix camera in new browsers and maintain backward compatibility
