components/GridToolBox/index.js
In GridToolBox component when there is only a search field available to user there is no need for filter by label on the left. Instead this label is needed when there are several options for filtering available
=> fix: UIS-396 remove filterBy label when there is only a searchbox

components/SearchBox/style.css
this is needed to make searchbox label styles like the labels in other components. for example input or dropdown
=> fix: searchbox styling

components/Preloader/index.js
set z-index of preload window to be ot top of other windows except error.
ErrorWindow has z-index = 9999. PreloadWindow has z-index = 9998
=> fix: preload window to be on top of all windows except error window

components/Accordion/index.js, components/Box/index.js
My current project requires the use of different glyph icons for collapse and expand.
The current implementation doesn't allow use of custom.
=> Extended accordion to support multiple arrow directions

components/Accordion/index.js
This fixes an issue with maker/checker compare grid sections not being open in some cases.
=> fix: UIS-1224: change Accordion's component state when new props are received

components/Input/validators/input.js, containers/TabContainer/validator.js, validator/constants.js
This is needed for Products - when creating (or editing) a Product, its name should not be equal to the name of an already existing Product (case-insensitive).
e.g.: I have a product named Test, and if i want to create another product named Test or test a validation error should be thrown.
=> fix: UIS-2920: add support for case-insensitive unique validation

containers/TabContainer/index.js, containers/TabContainer/validator.js
This fixes a bug in ```TabContainer``` where when you click on an action button three times it will successfully go through the frontend validations and execute the action. It happened on every sequential third press and only if no changes occurred between presses (no fields were touched).
The problem was that the same reference was used for an array which was later mutated using ```.pop()``` in one place while being used for validations in another.
=> Fixed a bug where every third press on a TabContainer's action button would always pass validations

components/Input/MoneyInput.js, components/Input/index.js, constants.js, helpers.js
Added input value lifecycle methods to Input - format, parse (opposite of format) and normalize.
Input component can now use Cleave.js input to format the value.
Passing Input the "options" prop will make it use Cleave's input.
Added exported settings for a Cleave.js money field.
Added MoneyInput - a wrapper over TextField that provides the Cleave settings for a money field.
Added exported function for formatting money values that are not in inputs.
Closes UA-78
=> fix(UA-78): Money values should be formatted

components/Documents/helpers.js, containers/Documents/reducer.js, containers/DocumentsObject/helpers.js, containers/DocumentsObject/reducer.js
- statuses set during the document replacement process are set according
to the standard flow - after the change the document becomes pending,
after approval - Active
Closes ABTN-3334
=> fix(ABTN-3334) : [ABZ] Documents: Replace button is missing

containers/TabContainer/index.js
- Add check in tab container to render activeTab content only in case
activeTab is not undefined
Closes ABTN-3836
=> fix(ABTN-3836) : [ABZ] System Alerts: Uncaught TypeError: Cannot read property 'styleContentWrapper' of undefined

components/Documents/helpers.js
- in case of delete, remove the document from documents array,
if it is changed
Closes CEM-1922
=> fix (CEM-1922): PAP / Document Management: Details for the deleted document is shown twice in the Validation screen

components/DocumentUpload/Camera.js
Image cannot be taken with the camera.
- window.URL.createObjectURL is depricated,
so set srcObject to the MediaStream directly
=> fix(CEM-2912): [PAP][Add Document]

components/ConfirmDialog/index.js, components/StatusDialog/index.js, package.json
Fixing the following issues:
As a legacy we are using the material-ui components directly and on other hand for other dialogs we have custom implementation. This merge requests represents a fix where the behavior is the same as it has been previously.
=> fix: confirm and status dialogs are not showing

components/Text/index.js
Business units and Users Edit screens open ConfirmationModal without message.
ConfirmationModal renders <Text>{message}</Text> leading React error for not allowing undefine to be rendered.
=> fix: render "null" in case of no children

components/Tab/Tab.js, components/Tab/styles.css
Used in: 
https://github.com/softwaregroup-bg/ut-front-react/blob/master/components/HeaderNew/HeaderProfileInfo.js#L50-L54
Previous behaviour:
How it currently looks:
=> fix: help menu link should not change users page

components/MaterialUILayout/index.js, components/PageLayout/style.css
От миграцията към нов material-ui насам, всички заглавия бяха разполовени и цялостно съдържанието на порталите бе станало по-разкрачено.
Разгледах какво е имало "някога" и слагам 2 промени, за да стане "както беше".
**Преди корекцията:**
**След корекцията:**
=> fix: Page Headings displayed cut in half

components/Layout/verticalStyles.css
Fix vertical scrolling on NMB during agent onboarding. On small screens, navigation buttons for next/previous are not visible
as in the image below. notice the absence of scroll bars
The expexted behaviour that this PR introduces is as follows where it is possible to scroll to the navigation footer
=> fix vertical scrolling on agent onboarding

components/TabMenu/style.css
**Before:**
**After:**
FYI @behrindzhambaz / @BozhidarTodorov / @pavelGeorgievSG
=> fix (PSTB-4685): improve misaligned and underlined tabs

components/Input/index.js
Fixes the issue of comma inputs by removing a default implemetation of the function of renderInput in ut-fron react
=> fix(PAP) fix unable to input comma issue UNMB-113

components/SimpleGrid/Body/Column.js
Using the `transformValue` is the `SimpleGrid` component , its possible to provide a value that is customised or to provide a value and custom styling for the Table Cell by havind the  ```transformValue``` function take the folowing signature
```
function transformValue(value, field, data, false, recordIndex) {
.//... function logic
return {
value,
style   // this is a valid jsx style object
}
```
or the current
```
function transformValue(value, field, data, false, recordIndex) {
.//... function logic
return value
}
```
=> Add ability to add cutom styling to Grid Table cells

components/DocumentUpload/index.js, package.json, ui/Store.js
- Handle new name  of the devtools extension - window.__REDUX_DEVTOOLS_EXTENSION__ (valid since verison 2.7 of the redux dev tools)
=> fix (ECNT-9999) : Add name of devtools extension

components/Loader/styles.css
This has been driving me nuts for a long time - the **spinner loader animation was not working**.
Not sure what happened some time ago in css-loader or postcss or ut-weback, but the animation shorthand property was breaking the animation, causing the name of the animation to be localised.
With this fix, the animation works.
FYI @NKozhuharski @BozhidarTodorov @pavelGeorgievSG
=> fix (AAA-000): loader animation not spinning

components/DatePicker/style.css
=> fix(MSA-2836): Different font size and different left spacing between Text Fields and Date Pickers

assets/index.css
Solves jira ticket MSA-2966.
When a user enters the portal when their laptop display size is scaled to 150% or 175% a vertical view is shown. This fixes that. The only problem was that the table would extend beyond the screen width which is fixed in a separate PR in the `ut-customer` repo.
=> fix(msa-2966): Changed vertical view to not be shown above 1023 px width

components/LoginPage/index.js, components/LoginPage/styles.css, containers/LoginForm/actions.js, containers/LoginForm/reducer.js, containers/VersionNumber/default-config.css, containers/VersionNumber/index.js, containers/VersionNumber/styles.css
This PR introduces a new version number component on the login page, displayed after the credentials box. The version number is dynamically fetched from the `x-ut-version` header, which is returned in the cookie check and logout requests. This allows users and developers to easily identify the current version of the application.
- Added a version number component to the login page UI
- The version is retrieved via the `x-ut-version` header on relevant API calls
- Display occurs after the credentials input box
Prerequisites
Version of ut-port-jsonrpc including [this](https://github.com/softwaregroup-bg/ut-port-jsonrpc/pull/33) pull request.
=> feat: added version number component on Login page
